import type { UiV2Projection } from "./types";

export const uiV2Fixture: UiV2Projection = {
  source: "fixture",
  project: {
    name: "Task Board Generator",
    slug: "generated-projects/task-board",
    status: "Developing",
    activeGroup: "Development Group",
    progress: "Slice 2 / 3",
  },
  composer: {
    mode: "gate_decision",
    reason: "Resolve dangerous_operation to continue.",
    disabled: false,
    readOnly: false,
  },
  orchestration: {
    orchestratorStatus: "running",
    activeGroup: "Development Group",
    activeAgent: "Coding Agent",
    unit: "Slice 2 / 3",
    phase: "Act",
    blocker: "dangerous_operation",
    nextAction: "Approve command, revise instruction, or reject",
  },
  requirementSnapshot: {
    raw: "Build an internal task board web app with projects, tasks, status transitions, and acceptance report.",
    normalized:
      "Task board web app: manage projects, tasks, status transitions, and generate acceptance reports.",
    score: 92,
    facts: ["Roles confirmed", "TDD enabled"],
    upcoming: ["Deployment confirmation"],
  },
  groups: [
    {
      id: "orchestrator",
      label: "Orchestrator Agent",
      summary: "Coordinates user intent, gates, and child agent handoffs.",
      status: "running",
    },
    {
      id: "requirement",
      label: "Requirement Group",
      summary: "Requirement package confirmed and locked for development.",
      status: "completed",
    },
    {
      id: "development",
      label: "Development Group",
      summary: "Implementing function slices with governed tool usage.",
      status: "gated",
    },
  ],
  runs: [
    {
      id: "orchestrator-handoff",
      agentId: "orchestrator",
      agentName: "Orchestrator Agent",
      groupId: "orchestrator",
      groupLabel: "Orchestrator",
      role: "Primary user interface",
      status: "completed",
      currentStep: "Reflect",
      summary: "Confirmed PRD handoff and started the Development Group.",
      steps: [
        {
          name: "Plan",
          summary: "Route confirmed PRD into development workflow.",
          status: "completed",
        },
        {
          name: "Act",
          summary: "Started Development Group and loaded latest acceptance criteria.",
          status: "completed",
        },
        { name: "Observe", summary: "Tech plan gate approved by user.", status: "completed" },
        {
          name: "Reflect",
          summary: "Development can proceed by function slice.",
          status: "completed",
        },
      ],
      tools: ["project.status", "gate.resolve"],
      diffs: [],
      tests: [],
      artifacts: ["PRD v2", "Acceptance criteria v2"],
      firstSeq: 1,
      lastSeq: 8,
    },
    {
      id: "architect-plan",
      agentId: "architect",
      agentName: "Architect Agent",
      groupId: "development",
      groupLabel: "Development Group",
      role: "Technical plan",
      status: "completed",
      currentStep: "Reflect",
      summary: "Selected Next.js, SQLite, and Playwright acceptance strategy.",
      steps: [
        {
          name: "Plan",
          summary: "Define stack, data model, and TDD strategy.",
          status: "completed",
        },
        {
          name: "Act",
          summary: "Generated technical plan and deployment approach.",
          status: "completed",
        },
        { name: "Observe", summary: "User approved tech_plan_confirm gate.", status: "completed" },
        { name: "Reflect", summary: "Plan ready for slice breakdown.", status: "completed" },
      ],
      tools: ["tech_plan.write"],
      diffs: [],
      tests: [],
      artifacts: ["Tech plan v1"],
      firstSeq: 9,
      lastSeq: 16,
    },
    {
      id: "planner-slices",
      agentId: "planner",
      agentName: "Planner Agent",
      groupId: "development",
      groupLabel: "Development Group",
      role: "Slice queue",
      status: "completed",
      currentStep: "Reflect",
      summary: "Created three function slices and scoped checks.",
      steps: [
        { name: "Plan", summary: "Map acceptance cases to small commits.", status: "completed" },
        { name: "Act", summary: "Created slice-01, slice-02, and slice-03.", status: "completed" },
        { name: "Observe", summary: "Queue is ready, slice-02 is active.", status: "completed" },
        { name: "Reflect", summary: "No replan required.", status: "completed" },
      ],
      tools: ["task_queue.write"],
      diffs: [],
      tests: [],
      artifacts: ["Slice queue"],
      firstSeq: 17,
      lastSeq: 24,
    },
    {
      id: "coding-slice-2",
      agentId: "coding",
      agentName: "Coding Agent",
      groupId: "development",
      groupLabel: "Development Group",
      role: "Implementation",
      status: "gated",
      currentStep: "Act",
      summary: "Writing failing tests and implementing task status transitions.",
      steps: [
        {
          name: "Plan",
          summary: "Add task transition tests and board interaction.",
          status: "completed",
        },
        {
          name: "Act",
          summary: "Requests package install before writing generated UI files.",
          status: "gated",
        },
        {
          name: "Observe",
          summary: "Waiting for dangerous operation decision.",
          status: "waiting",
        },
        { name: "Reflect", summary: "Pending after command decision.", status: "pending" },
      ],
      tools: ["shell.run", "file.write", "opencode.permission"],
      diffs: ["apps/generated/tasks/page.tsx +86", "tests/task-transitions.test.ts +42"],
      tests: ["Vitest pending", "Playwright pending"],
      artifacts: [],
      firstSeq: 25,
      lastSeq: 32,
      risk: "High external download requires human confirmation.",
    },
    {
      id: "qa-mobile-overflow",
      agentId: "qa",
      agentName: "QA Agent",
      groupId: "development",
      groupLabel: "Development Group",
      role: "Verification",
      status: "failed",
      currentStep: "Observe",
      summary: "Playwright found a mobile toolbar overflow in the generated preview.",
      steps: [
        { name: "Plan", summary: "Run final visual checks for active slice.", status: "completed" },
        { name: "Act", summary: "Executed Playwright viewport checks.", status: "completed" },
        { name: "Observe", summary: "Mobile overflow at 390px width.", status: "failed" },
        { name: "Reflect", summary: "Request fix after coding gate resolves.", status: "waiting" },
      ],
      tools: ["playwright.run"],
      diffs: [],
      tests: ["Playwright failed", "4 checks passed"],
      artifacts: ["trace: mobile-button-overflow.spec.ts"],
      firstSeq: 33,
      lastSeq: 40,
    },
  ],
  currentWork: {
    primaryRunId: "coding-slice-2",
    relatedRunIds: ["coding-slice-2", "qa-mobile-overflow"],
    gateId: "gate-dangerous-install",
    status: "gated",
    summary: "Approve command, revise instruction, or reject",
  },
  runGroups: [
    {
      id: "orchestrator",
      label: "Orchestrator Agent",
      status: "completed",
      runIds: ["orchestrator-handoff"],
      failedCount: 0,
      active: false,
    },
    {
      id: "development",
      label: "Development Group",
      status: "gated",
      runIds: ["qa-mobile-overflow", "coding-slice-2", "planner-slices", "architect-plan"],
      failedCount: 1,
      active: true,
    },
  ],
  streamItems: [
    {
      id: "user-raw",
      seq: 1,
      type: "user",
      title: "You - initial requirement",
      summary:
        "Build an internal task board web app with projects, tasks, status transitions, and acceptance report.",
      timestamp: "09:12",
    },
    {
      id: "orch-handoff",
      seq: 2,
      type: "orchestrator",
      title: "Orchestrator - handoff",
      summary:
        "Requirement package is confirmed. Starting Development Group with approved tech plan.",
      timestamp: "09:18",
      runId: "orchestrator-handoff",
      severity: "success",
    },
    {
      id: "architect",
      seq: 3,
      type: "agent-run",
      title: "Architect Agent - technical plan",
      summary: "Stack, data model, TDD strategy, and preview plan approved.",
      timestamp: "09:21",
      runId: "architect-plan",
      tab: "Report",
      severity: "success",
    },
    {
      id: "planner",
      seq: 4,
      type: "agent-run",
      title: "Planner Agent - slice queue",
      summary: "Created 3 function slices. Slice 2 is active: task status transitions.",
      timestamp: "09:24",
      runId: "planner-slices",
      severity: "success",
    },
    {
      id: "coding",
      seq: 5,
      type: "agent-run",
      title: "Coding Agent - Act",
      summary:
        "Writing failing tests, preparing generated task board UI, and requesting shell permission.",
      timestamp: "09:31",
      runId: "coding-slice-2",
      tab: "Files",
      severity: "warning",
    },
    {
      id: "tool-permission",
      seq: 6,
      type: "tool",
      title: "Tool request - shell.run",
      summary: "npm install @dnd-kit/core. Risk grade: High external download.",
      timestamp: "09:31",
      runId: "coding-slice-2",
      tab: "Terminal",
      severity: "warning",
    },
    {
      id: "gate",
      seq: 7,
      type: "gate",
      title: "Dangerous operation gate",
      summary: "Human decision required before the Coding Agent can continue.",
      timestamp: "09:32",
      runId: "coding-slice-2",
      severity: "danger",
    },
    {
      id: "qa",
      seq: 8,
      type: "test",
      title: "QA Agent - Observe",
      summary: "Playwright mobile check failed; trace is linked in Tests.",
      timestamp: "09:36",
      runId: "qa-mobile-overflow",
      tab: "Tests",
      severity: "danger",
    },
  ],
  swimlaneRows: [
    {
      id: "orchestrator",
      groupId: "orchestrator",
      agentName: "Orchestrator",
      role: "User interface",
      status: "running",
      cells: [
        {
          agentId: "orchestrator",
          step: "Plan",
          summary: "Route workflow",
          status: "completed",
          runId: "orchestrator-handoff",
        },
        {
          agentId: "orchestrator",
          step: "Act",
          summary: "Start dev group",
          status: "completed",
          runId: "orchestrator-handoff",
        },
        {
          agentId: "orchestrator",
          step: "Observe",
          summary: "Gate open",
          status: "gated",
          runId: "coding-slice-2",
          chips: ["gate"],
        },
        {
          agentId: "orchestrator",
          step: "Reflect",
          summary: "Await user",
          status: "waiting",
          runId: "coding-slice-2",
        },
      ],
    },
    {
      id: "coding",
      groupId: "development",
      agentName: "Coding",
      role: "Development",
      status: "gated",
      cells: [
        {
          agentId: "coding",
          step: "Plan",
          summary: "slice-02",
          status: "completed",
          runId: "coding-slice-2",
        },
        {
          agentId: "coding",
          step: "Act",
          summary: "permission",
          fullSummary:
            "Requests package installation permission before writing generated UI files and continuing the active implementation slice.",
          status: "gated",
          runId: "coding-slice-2",
          chips: ["tool", "gate"],
          links: ["Terminal", "Files", "Tests"],
          firstSeq: 25,
          lastSeq: 32,
        },
        {
          agentId: "coding",
          step: "Observe",
          summary: "waiting",
          status: "waiting",
          runId: "coding-slice-2",
        },
        {
          agentId: "coding",
          step: "Reflect",
          summary: "pending",
          status: "pending",
          runId: "coding-slice-2",
        },
      ],
    },
    {
      id: "qa",
      groupId: "development",
      agentName: "QA",
      role: "Development",
      status: "failed",
      cells: [
        {
          agentId: "qa",
          step: "Plan",
          summary: "checks",
          status: "completed",
          runId: "qa-mobile-overflow",
        },
        {
          agentId: "qa",
          step: "Act",
          summary: "Playwright",
          status: "completed",
          runId: "qa-mobile-overflow",
        },
        {
          agentId: "qa",
          step: "Observe",
          summary: "1 failed",
          status: "failed",
          runId: "qa-mobile-overflow",
          chips: ["test"],
        },
        {
          agentId: "qa",
          step: "Reflect",
          summary: "fix after gate",
          status: "waiting",
          runId: "qa-mobile-overflow",
        },
      ],
    },
    {
      id: "architect",
      groupId: "development",
      agentName: "Architect",
      role: "Development",
      status: "completed",
      cells: [
        {
          agentId: "architect",
          step: "Plan",
          summary: "Tech plan",
          status: "completed",
          runId: "architect-plan",
        },
        {
          agentId: "architect",
          step: "Act",
          summary: "TDD plan",
          status: "completed",
          runId: "architect-plan",
        },
        {
          agentId: "architect",
          step: "Observe",
          summary: "Approved",
          status: "completed",
          runId: "architect-plan",
        },
        {
          agentId: "architect",
          step: "Reflect",
          summary: "Slice ready",
          status: "completed",
          runId: "architect-plan",
        },
      ],
    },
    {
      id: "planner",
      groupId: "development",
      agentName: "Planner",
      role: "Development",
      status: "completed",
      cells: [
        {
          agentId: "planner",
          step: "Plan",
          summary: "Slices",
          status: "completed",
          runId: "planner-slices",
        },
        {
          agentId: "planner",
          step: "Act",
          summary: "Queue",
          status: "completed",
          runId: "planner-slices",
        },
        {
          agentId: "planner",
          step: "Observe",
          summary: "3 tasks",
          status: "completed",
          runId: "planner-slices",
        },
        {
          agentId: "planner",
          step: "Reflect",
          summary: "No replan",
          status: "completed",
          runId: "planner-slices",
        },
      ],
    },
    {
      id: "intake",
      groupId: "requirement",
      agentName: "Intake",
      role: "Requirement",
      status: "completed",
      cells: [
        { agentId: "intake", step: "Plan", summary: "Normalize", status: "completed" },
        { agentId: "intake", step: "Act", summary: "Read raw need", status: "completed" },
        { agentId: "intake", step: "Observe", summary: "Complete", status: "completed" },
        { agentId: "intake", step: "Reflect", summary: "Hand off", status: "completed" },
      ],
    },
    {
      id: "analyst",
      groupId: "requirement",
      agentName: "Analyst",
      role: "Requirement",
      status: "completed",
      cells: [
        { agentId: "analyst", step: "Plan", summary: "Extract flows", status: "completed" },
        { agentId: "analyst", step: "Act", summary: "5 features", status: "completed" },
        { agentId: "analyst", step: "Observe", summary: "3 pages", status: "completed" },
        { agentId: "analyst", step: "Reflect", summary: "No critical gap", status: "completed" },
      ],
    },
  ],
  openGate: {
    id: "gate-dangerous-install",
    type: "dangerous_operation",
    title: "Dangerous operation",
    description: "Coding Agent wants to run a high-risk external download before continuing.",
    risk: "high",
    command: "npm install @dnd-kit/core",
    options: [
      { id: "approve", label: "Approve command", tone: "primary" },
      { id: "revise", label: "Revise instruction", tone: "secondary" },
      { id: "reject", label: "Reject", tone: "danger" },
    ],
  },
  tests: [
    { name: "TypeScript", detail: "0 errors", status: "passed" },
    { name: "Vitest unit", detail: "31 tests", status: "passed" },
    { name: "Build", detail: "8.2s", status: "passed" },
    {
      name: "Playwright",
      detail: "mobile overflow",
      status: "failed",
      linkedRunId: "qa-mobile-overflow",
    },
    { name: "Acceptance", detail: "awaiting fix", status: "pending" },
  ],
  files: [
    { path: "apps/generated/tasks/page.tsx", status: "changed" },
    { path: "tests/task-transitions.test.ts", status: "created" },
    { path: "artifacts/prd-v2.md", status: "artifact" },
    { path: "artifacts/playwright/mobile-button-overflow.zip", status: "artifact" },
  ],
  previewUrl: "localhost:5173/preview",
  terminalItems: [
    {
      title: "npm install @dnd-kit/core",
      summary: "risk: high external download / waiting for dangerous_operation gate",
    },
  ],
  reportArtifacts: [
    "PRD v2",
    "Acceptance criteria",
    "Tech plan",
    "Risk summary",
    "Delivery report",
  ],
};
