import type { IntegrationDefinition } from "@oc/shared";

export const P1_INTEGRATION_DEFINITIONS: IntegrationDefinition[] = [
  {
    id: "playwright",
    version: "1.0.0",
    protocol: "native",
    mode: "remote",
    displayName: "Playwright / Browser",
    description: "Preview verification, screenshots, console errors, and traces",
    toolAllowlist: ["screenshot", "console_errors", "navigate"],
    permissions: ["read", "network"],
    riskLevel: "medium",
    secretRefs: [],
    offlineFallbackSkillPackId: "playwright-offline",
    highRiskTools: ["navigate"],
  },
  {
    id: "figma",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "Figma",
    description: "Design baseline and design-to-code context",
    toolAllowlist: ["get_design_context", "export_screenshot"],
    permissions: ["read"],
    riskLevel: "low",
    secretRefs: ["FIGMA_ACCESS_TOKEN"],
    offlineFallbackSkillPackId: "figma-offline",
  },
  {
    id: "github",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "GitHub",
    description: "Repository, branch, and PR handoff",
    toolAllowlist: ["list_repos", "create_branch", "open_pr", "read_issues"],
    permissions: ["read", "write"],
    riskLevel: "medium",
    secretRefs: ["GITHUB_TOKEN"],
    offlineFallbackSkillPackId: "github-offline",
    highRiskTools: ["open_pr"],
  },
  {
    id: "supabase",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "Supabase",
    description: "Dev project schema, migrations, and seed helpers",
    toolAllowlist: ["list_tables", "apply_migration", "seed_sql"],
    permissions: ["read", "write"],
    riskLevel: "high",
    secretRefs: ["SUPABASE_ACCESS_TOKEN"],
    offlineFallbackSkillPackId: "supabase-offline",
    highRiskTools: ["apply_migration", "seed_sql"],
  },
  {
    id: "vercel",
    version: "1.0.0",
    protocol: "native",
    mode: "remote",
    displayName: "Vercel",
    description: "Preview deployments, logs, and env readiness",
    toolAllowlist: ["list_projects", "create_preview_deploy", "read_logs"],
    permissions: ["read", "deploy", "secrets"],
    riskLevel: "high",
    secretRefs: ["VERCEL_TOKEN"],
    offlineFallbackSkillPackId: "vercel-offline",
    highRiskTools: ["create_preview_deploy"],
  },

  // ─── Development-assist MCPs (no secret, auto-available) ─────────────────
  // These are local/stdio MCP servers that need no OAuth or API key, so they
  // don't require a user-created connection record — callIntegrationTool
  // auto-enables definitions with empty secretRefs.
  {
    id: "codegraph",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "CodeGraph",
    description: "Code intelligence: call graphs, callers, callees, impact analysis",
    toolAllowlist: ["query", "callers", "callees", "impact", "status"],
    permissions: ["read"],
    riskLevel: "low",
    secretRefs: [],
  },
  {
    id: "context7",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "Context7 (library docs)",
    description: "Resolve and fetch up-to-date documentation for third-party libraries",
    toolAllowlist: ["resolve-library-id", "get-library-docs"],
    permissions: ["read", "network"],
    riskLevel: "low",
    secretRefs: [],
  },

  // ─── Web search MCP (requires Tavily API key) ────────────────────────────
  {
    id: "web-search",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "Web Search (Tavily)",
    description: "AI-oriented web search, extract, and crawl via Tavily",
    toolAllowlist: ["tavily-search", "tavily-extract"],
    permissions: ["read", "network"],
    riskLevel: "low",
    secretRefs: ["TAVILY_API_KEY"],
  },
];
