import type { IntegrationDefinition } from "@oc/shared";

export const P1_INTEGRATION_DEFINITIONS: IntegrationDefinition[] = [
  {
    id: "playwright",
    version: "1.0.0",
    protocol: "native",
    mode: "remote",
    displayName: "Playwright / Browser",
    description: "Preview verification, screenshots, console errors, and traces",
    toolAllowlist: ["screenshot", "console_errors", "navigate"],
    permissions: ["read", "network"],
    riskLevel: "medium",
    secretRefs: [],
    offlineFallbackSkillPackId: "playwright-offline",
    highRiskTools: ["navigate"],
  },
  {
    id: "figma",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "Figma",
    description: "Design baseline and design-to-code context",
    toolAllowlist: ["get_design_context", "export_screenshot"],
    permissions: ["read"],
    riskLevel: "low",
    secretRefs: ["FIGMA_ACCESS_TOKEN"],
    offlineFallbackSkillPackId: "figma-offline",
  },
  {
    id: "github",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "GitHub",
    description: "Repository, branch, and PR handoff",
    toolAllowlist: ["list_repos", "create_branch", "open_pr", "read_issues"],
    permissions: ["read", "write"],
    riskLevel: "medium",
    secretRefs: ["GITHUB_TOKEN"],
    offlineFallbackSkillPackId: "github-offline",
    highRiskTools: ["open_pr"],
  },
  {
    id: "supabase",
    version: "1.0.0",
    protocol: "mcp",
    mode: "remote",
    displayName: "Supabase",
    description: "Dev project schema, migrations, and seed helpers",
    toolAllowlist: ["list_tables", "apply_migration", "seed_sql"],
    permissions: ["read", "write"],
    riskLevel: "high",
    secretRefs: ["SUPABASE_ACCESS_TOKEN"],
    offlineFallbackSkillPackId: "supabase-offline",
    highRiskTools: ["apply_migration", "seed_sql"],
  },
  {
    id: "vercel",
    version: "1.0.0",
    protocol: "native",
    mode: "remote",
    displayName: "Vercel",
    description: "Preview deployments, logs, and env readiness",
    toolAllowlist: ["list_projects", "create_preview_deploy", "read_logs"],
    permissions: ["read", "deploy", "secrets"],
    riskLevel: "high",
    secretRefs: ["VERCEL_TOKEN"],
    offlineFallbackSkillPackId: "vercel-offline",
    highRiskTools: ["create_preview_deploy"],
  },
];
