import type { AgentDefinition, Db } from "@oc/shared";
import { registerAgent } from "../../registry.js";

const AGENT_VERSION = "1.0.0";

export const DEVELOPMENT_AGENT_IDS = {
  architect: `architect@${AGENT_VERSION}`,
  planner: `planner@${AGENT_VERSION}`,
  coding: `coding@${AGENT_VERSION}`,
  review: `review@${AGENT_VERSION}`,
  qa: `qa@${AGENT_VERSION}`,
  devopsDelivery: `devops-delivery@${AGENT_VERSION}`,
} as const;

export const DEVELOPMENT_AGENT_DEFINITIONS: AgentDefinition[] = [
  {
    id: "architect",
    version: AGENT_VERSION,
    group: "development",
    role: "架构师 Agent",
    description: "产出含 Web 前端层的可执行技术方案",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    tools: ["read-artifact@1.0.0", "workspace-read@1.0.0"],
    modelPolicy: { tier: "strong" },
    riskLevel: "low",
    permissions: ["read"],
    executor: "scripted",
    capabilities: ["tech-plan", "architecture-design"],
    defaultInputSummary: "需求阶段产出的 PRD 与验收标准",
    outputHandoff: "技术方案（技术栈/架构/数据模型/TDD 策略）；经 tech_plan_confirm Gate 后交给 Planner 拆切片",
  },
  {
    id: "planner",
    version: AGENT_VERSION,
    group: "development",
    role: "切片规划 Agent",
    description: "把验收标准拆分为含 Web UI 交付物与 vitest 测试的有序功能切片",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    tools: [],
    modelPolicy: { tier: "strong" },
    riskLevel: "low",
    permissions: ["read"],
    executor: "scripted",
    capabilities: ["slice-planning", "test-design"],
    defaultInputSummary: "已确认的技术方案",
    outputHandoff: "有序功能切片队列（每切片含目标/验收/测试命令），交给 Coding Agent 逐个实现",
  },
  {
    id: "coding",
    version: AGENT_VERSION,
    group: "development",
    role: "编码 Agent",
    description: "实现功能切片（含 Web 页面）并保证测试通过",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    tools: ["shell", "edit"],
    modelPolicy: { tier: "strong" },
    riskLevel: "medium",
    permissions: ["read", "write"],
    executor: "scripted",
    capabilities: ["tdd-implementation", "web-ui-development"],
    defaultInputSummary: "单个功能切片的目标 + 验收检查 + 测试命令",
    outputHandoff: "切片代码改动；交给 Review 审查，并由平台权威测试独立判定是否通过",
  },
  {
    id: "review",
    version: AGENT_VERSION,
    group: "development",
    role: "代码审查 Agent",
    description: "审查切片改动的正确性与一致性",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    tools: [],
    modelPolicy: { tier: "strong" },
    riskLevel: "low",
    permissions: ["read"],
    executor: "scripted",
    capabilities: ["code-review"],
    defaultInputSummary: "刚提交的切片 diff + 验收检查",
    outputHandoff: "审查结论（approved/findings）；findings 回流给 Coding Agent 作为下一次修复的依据",
  },
  {
    id: "qa",
    version: AGENT_VERSION,
    group: "development",
    role: "质量验证 Agent",
    description: "验证 Preview 展示真实产品 Web UI，可调用受管控的集成工具",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    tools: [],
    modelPolicy: { tier: "standard" },
    riskLevel: "medium",
    permissions: ["read", "network"],
    executor: "scripted",
    integrationAccess: "auto",
    capabilities: ["qa-verification", "preview-check"],
    defaultInputSummary: "全切片完成后的应用 + 预览 URL",
    outputHandoff: "QA 结论（通过/失败 + 原因）；失败回到开发循环，通过交给 DevOps 进入交付",
  },
  {
    id: "devops-delivery",
    version: AGENT_VERSION,
    group: "development",
    role: "交付运维 Agent",
    description: "汇总交付产物并撰写含浏览器访问方式的部署说明",
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    tools: [],
    modelPolicy: { tier: "standard" },
    riskLevel: "low",
    permissions: ["read"],
    executor: "scripted",
    capabilities: ["delivery-packaging", "deployment-docs"],
    defaultInputSummary: "通过测试的应用 + 部署 URL",
    outputHandoff: "交付包（运行说明/Docker/交付报告）；等待用户最终验收",
  },
];

export function registerDevelopmentAgents(db: Db): void {
  for (const definition of DEVELOPMENT_AGENT_DEFINITIONS) {
    registerAgent(db, definition);
  }
}
